/*
  Generic SRID and geometry type audit.
  Replace YOUR_TABLE and GEOM_COLUMN.
*/

SELECT t.GEOM_COLUMN.SDO_SRID AS srid, COUNT(*) AS feature_count
FROM YOUR_TABLE t
WHERE t.GEOM_COLUMN IS NOT NULL
GROUP BY t.GEOM_COLUMN.SDO_SRID
ORDER BY t.GEOM_COLUMN.SDO_SRID;

SELECT t.GEOM_COLUMN.SDO_GTYPE AS sdo_gtype, COUNT(*) AS feature_count
FROM YOUR_TABLE t
WHERE t.GEOM_COLUMN IS NOT NULL
GROUP BY t.GEOM_COLUMN.SDO_GTYPE
ORDER BY t.GEOM_COLUMN.SDO_GTYPE;
